# Generated by Django 5.2.8 on 2025-11-13 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nome_completo', models.CharField(max_length=150)),
                ('nome_venda', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('local_principal_venda', models.CharField(help_text='Ex.: Saída do bandejão, prainha, etc.', max_length=100)),
                ('status_disponivel', models.BooleanField(default=False, help_text='Toggle Disponível / Indisponível do perfil')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, help_text='Arquivo da figura (brigadeiro, brownie, etc.)', null=True, upload_to='produtos/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True)),
                ('status_disponivel', models.BooleanField(default=True, help_text='Disponível / Indisponível na tela de produto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='appWeb.vendedor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
