# Generated by ChatGPT - manual migration to add fields and ImagemProduto
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Conta ativa após confirmação por e-mail'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.ImageField(upload_to='vendedores/perfis/', null=True, blank=True),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/catalogo/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_catalogo', to='appWeb.produto')),
            ],
        ),
    ]
