# Generated by Django 5.2.8 on 2025-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_alter_produto_imagem_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='vendedores/perfis/'),
        ),
    ]
