# Generated by Django 5.2.7 on 2025-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_vendedor_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Conta ativa após confirmação por e-mail'),
        ),
    ]
