"""
Django settings for projetoRP2 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qeg0km3@gctj7-zy%_3l8&nnwkuv6%_2p9xbv4o%h%vz96tjui'

# SECURITY WARNING: don't run with debug turned on in production!
# Read DEBUG and ALLOWED_HOSTS from environment so Heroku can set them securely.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Example: set ALLOWED_HOSTS env var to 'your-app.herokuapp.com,localhost'
_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if _hosts_env:
    # split on commas, strip whitespace, ignore empty entries
    ALLOWED_HOSTS = [h.strip() for h in _hosts_env.split(',') if h.strip()]
    # allow wildcard '*' to mean allow all hosts
    if '*' in ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*']
else:
    # sensible defaults for local development
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# If CLOUDINARY_URL is provided, use Cloudinary for media storage (prevents
# relying on Heroku ephemeral filesystem). Set CLOUDINARY_URL env var like:
# cloudinary://API_KEY:API_SECRET@CLOUD_NAME
if os.environ.get('CLOUDINARY_URL'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'appWeb',
    'anymail',
    # Cloudinary storage for media (optional, enabled when CLOUDINARY_URL is set)
    'cloudinary',
    'cloudinary_storage',
]

# Optional: Anymail (SendGrid) support. If installed and SENDGRID_API_KEY is set
# we will switch the EMAIL_BACKEND to Anymail's SendGrid backend below.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projetoRP2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projetoRP2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# On Heroku the DATABASE_URL env var will be provided by the Heroku Postgres addon.
# dj-database-url parses that URL into Django's DATABASES setting. When DATABASE_URL
# is not set (local development) we fall back to a local sqlite database.
DATABASES = {
    'default': dj_database_url.config(
        default=str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        engine='django.db.backends.sqlite3'
    )
}

# If dj_database_url returned a simple path string for sqlite, ensure proper ENGINE.
if DATABASES['default'].get('ENGINE', '').endswith('sqlite3') and 'NAME' not in DATABASES['default']:
    DATABASES['default']['NAME'] = str(BASE_DIR / 'db.sqlite3')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Where `collectstatic` will collect static files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Additional places Django will look for static files (optional)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Use WhiteNoise storage backend so Heroku can serve compressed files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Development email backend: prints emails to console. Change for production.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@localhost')

# Prefer provider API (SendGrid via Anymail) when API key is provided in env.
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
if SENDGRID_API_KEY:
    ANYMAIL = {
        'SENDGRID_API_KEY': SENDGRID_API_KEY,
    }
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'

# Optional: configure SMTP details when EMAIL_HOST is provided in env (fallback)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
if EMAIL_HOST and not SENDGRID_API_KEY:
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    # use Django's SMTP backend explicitly when SMTP settings are provided
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Trust X-Forwarded-Proto header (useful on Heroku behind proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
